// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_center_distribuidora.Context;

#nullable disable

namespace webcenterdistribuidora.Migrations
{
    [DbContext(typeof(CrmContext))]
    [Migration("20230131201421_InitialCrmMigration")]
    partial class InitialCrmMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("web_center_distribuidora.ModelsCrm.CrmEstoque", b =>
                {
                    b.Property<int>("Chave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Chave_Produto")
                        .HasColumnType("int");

                    b.Property<int>("Competencia")
                        .HasColumnType("int");

                    b.Property<int>("Disp_It")
                        .HasColumnType("int");

                    b.HasKey("Chave");

                    b.ToTable("Estoques");
                });

            modelBuilder.Entity("web_center_distribuidora.ModelsCrm.CrmGrupo", b =>
                {
                    b.Property<int>("Chave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao_Web")
                        .HasColumnType("longtext");

                    b.Property<bool>("Grupo_Web")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.HasKey("Chave");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("web_center_distribuidora.ModelsCrm.CrmMovimentacao", b =>
                {
                    b.Property<int>("Chave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cfop")
                        .HasColumnType("longtext");

                    b.Property<int>("CondPag")
                        .HasColumnType("int");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Empresa")
                        .HasColumnType("int");

                    b.Property<DateTime>("Lancamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Modelo")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Pessoa")
                        .HasColumnType("longtext");

                    b.Property<int>("Nota_Fiscal")
                        .HasColumnType("int");

                    b.Property<int>("Pessoa")
                        .HasColumnType("int");

                    b.Property<string>("Serie")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Sub_Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Usuario")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorProdutos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Vendedor")
                        .HasColumnType("int");

                    b.HasKey("Chave");

                    b.ToTable("Movimentacao");
                });

            modelBuilder.Entity("web_center_distribuidora.ModelsCrm.CrmMovimentacaoItem", b =>
                {
                    b.Property<int>("Chave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChaveMov")
                        .HasColumnType("int");

                    b.Property<int>("Codigo_Produto")
                        .HasColumnType("int");

                    b.Property<DateTime>("Lancamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("Tipo_Operacao")
                        .HasColumnType("int");

                    b.HasKey("Chave");

                    b.ToTable("MovItens");
                });

            modelBuilder.Entity("web_center_distribuidora.ModelsCrm.CrmPessoa", b =>
                {
                    b.Property<int>("Chave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<string>("Cnpj_Cpf")
                        .HasColumnType("longtext");

                    b.Property<string>("Codigo")
                        .HasColumnType("longtext");

                    b.Property<string>("Fone")
                        .HasColumnType("longtext");

                    b.Property<bool>("Inativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Inclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("Nascimento_Abertura")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome_Fantasia")
                        .HasColumnType("longtext");

                    b.Property<string>("Rg_Ie")
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("Ultima_Atualizacao")
                        .HasColumnType("date");

                    b.HasKey("Chave");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("web_center_distribuidora.ModelsCrm.CrmPessoaContato", b =>
                {
                    b.Property<int>("Chave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Campo1")
                        .HasColumnType("longtext");

                    b.Property<int>("Chave_Pessoa")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.HasKey("Chave");

                    b.ToTable("Pessoas_Contatos");
                });

            modelBuilder.Entity("web_center_distribuidora.ModelsCrm.CrmPessoaEndereco", b =>
                {
                    b.Property<int>("Chave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .HasColumnType("longtext");

                    b.Property<int>("Chave_Pessoa")
                        .HasColumnType("int");

                    b.Property<int>("Cidade")
                        .HasColumnType("int");

                    b.Property<string>("Cidade_Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<bool>("Padrao")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Uf")
                        .HasColumnType("longtext");

                    b.HasKey("Chave");

                    b.ToTable("Pessoas_Enderecos");
                });

            modelBuilder.Entity("web_center_distribuidora.ModelsCrm.CrmProduto", b =>
                {
                    b.Property<int>("Chave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Auxiliar1")
                        .HasColumnType("longtext");

                    b.Property<string>("Codigo")
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int>("Fornecedor")
                        .HasColumnType("int");

                    b.Property<int>("Grupo1")
                        .HasColumnType("int");

                    b.Property<int>("Grupo2")
                        .HasColumnType("int");

                    b.Property<int>("Grupo3")
                        .HasColumnType("int");

                    b.Property<bool>("Inativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Inclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Preco_Atacado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Preco_Venda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Produto_Web")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Quant_Preco_Atacado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ult_Ven")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Unid_Med")
                        .HasColumnType("int");

                    b.HasKey("Chave");

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
