// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_center_distribuidora.Context;

#nullable disable

namespace webcenterdistribuidora.Migrations
{
    [DbContext(typeof(DefaultContext))]
    partial class DefaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("web_center_distribuidora.Models.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("informacaoContato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pessoaId")
                        .HasColumnType("int");

                    b.Property<int>("tipoContato")
                        .HasColumnType("int");

                    b.Property<bool>("whatsApp")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("pessoaId");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<string>("logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.Property<int>("pessoaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("pessoaId");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.Estoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("competencia")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<long>("estoqueDisponivel")
                        .HasColumnType("bigint");

                    b.Property<long>("estoqueReservado")
                        .HasColumnType("bigint");

                    b.Property<int>("produtoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("produtoId");

                    b.ToTable("Estoques");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("codigo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("inativo")
                        .HasColumnType("bit");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("codigoDeRastreamento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("dataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<int>("empresa")
                        .HasColumnType("int");

                    b.Property<int>("pessoaId")
                        .HasColumnType("int");

                    b.Property<int>("tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("pessoaId");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.NotaFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("cfop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dadosAdicionais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("desconto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("frete")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("movimentacaoId")
                        .HasColumnType("int");

                    b.Property<int>("numeroNota")
                        .HasColumnType("int");

                    b.Property<int>("serie")
                        .HasColumnType("int");

                    b.Property<decimal>("subTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("tipoNota")
                        .HasColumnType("int");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ufOrigem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("movimentacaoId");

                    b.ToTable("NotaFiscais");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ultimoAcesso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Pessoa");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Pessoa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("web_center_distribuidora.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("NotaFiscalId")
                        .HasColumnType("int");

                    b.Property<string>("codigo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("codigoSituacaoTributaria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("fornecedorId")
                        .HasColumnType("int");

                    b.Property<bool>("inativo")
                        .HasColumnType("bit");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("precoAtacado")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("precoVarejo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("quantidadeAtacado")
                        .HasColumnType("int");

                    b.Property<string>("unidadeDeMedida")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NotaFiscalId");

                    b.HasIndex("fornecedorId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.PessoaFisica", b =>
                {
                    b.HasBaseType("web_center_distribuidora.Models.Pessoa");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("dataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("rg")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("sexo")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("PessoaFisica");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.PessoaJuridica", b =>
                {
                    b.HasBaseType("web_center_distribuidora.Models.Pessoa");

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("dataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<string>("inscricaoEstadual")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("nomeFantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("razaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("PessoaJuridica");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.Contato", b =>
                {
                    b.HasOne("web_center_distribuidora.Models.Pessoa", "Pessoa")
                        .WithMany("Contatos")
                        .HasForeignKey("pessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.Endereco", b =>
                {
                    b.HasOne("web_center_distribuidora.Models.Pessoa", "Pessoa")
                        .WithMany("Enderecos")
                        .HasForeignKey("pessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.Estoque", b =>
                {
                    b.HasOne("web_center_distribuidora.Models.Produto", "Produto")
                        .WithMany("Estoque")
                        .HasForeignKey("produtoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.Grupo", b =>
                {
                    b.HasOne("web_center_distribuidora.Models.Produto", null)
                        .WithMany("Grupos")
                        .HasForeignKey("ProdutoId");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.Movimentacao", b =>
                {
                    b.HasOne("web_center_distribuidora.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("pessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.NotaFiscal", b =>
                {
                    b.HasOne("web_center_distribuidora.Models.Movimentacao", "Movimentacao")
                        .WithMany("notasFiscais")
                        .HasForeignKey("movimentacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimentacao");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.Produto", b =>
                {
                    b.HasOne("web_center_distribuidora.Models.NotaFiscal", null)
                        .WithMany("Produtos")
                        .HasForeignKey("NotaFiscalId");

                    b.HasOne("web_center_distribuidora.Models.PessoaJuridica", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("fornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.Movimentacao", b =>
                {
                    b.Navigation("notasFiscais");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.NotaFiscal", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.Pessoa", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("web_center_distribuidora.Models.Produto", b =>
                {
                    b.Navigation("Estoque");

                    b.Navigation("Grupos");
                });
#pragma warning restore 612, 618
        }
    }
}
